name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter o codigo do projeto
        uses: actions/checkout@v4.2.2
      - name: Autenticar no docker hub (Login to Docker Hub)

        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: construção da imagen docker (Build and push)

        uses: docker/build-push-action@v4
        with:
          context: ./src
          push: true
          file: src/Dockerfile
          tags: |
            levimodesto/fake-shop:latest
            levimodesto/fake-shop:v${{ github.run_number }}

  cd:
    runs-on: ubuntu-latest
    needs: [ci] 
    steps:
      - name: Autenticar aws
        run: echo "Executar o comando aws config"
      - name: configurar kubectl
        run: echo "executar  o comando aws eks update-kubeconfig"
      - name: Deploy dos manifestos no Kubernete
        run: echo "Executar o comando kubectl apply"
      
    
    
